language: python
services:
  docker
python:
  - "3.6"
 before install:
  pip3 install requests json jsonpickle
  docker build -t server-image -f /server/Dockerfile .
  docker run --p 8000:8000 server-image
script:
  - python3 test.py
